2023/04/13 08:59:14 [error] 20#20: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.32.1, server: heater-new.loc, request: "GET /internal/tests HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "heater-new.loc"
2023/04/13 08:59:15 [error] 20#20: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.32.1, server: heater-new.loc, request: "GET /internal/tests HTTP/1.1", upstream: "fastcgi://192.168.32.4:9000", host: "heater-new.loc"
2023/04/13 11:54:36 [error] 21#21: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET /internal/tests HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc"
2023/04/13 11:54:40 [error] 21#21: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET /debug HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc", referrer: "http://heater-new.loc/"
2023/04/13 11:54:50 [error] 22#22: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET /debug HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc", referrer: "http://heater-new.loc/"
2023/04/13 11:55:03 [error] 22#22: *3 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc"
2023/04/13 11:55:04 [error] 21#21: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET /api/get_rooms_data HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc", referrer: "http://heater-new.loc/"
2023/04/13 11:55:43 [error] 24#24: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc"
2023/04/13 11:55:43 [error] 21#21: *1 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET /api/get_rooms_data HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc", referrer: "http://heater-new.loc/"
2023/04/13 11:56:14 [error] 24#24: *5 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc"
2023/04/13 11:56:37 [error] 23#23: *12 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc"
2023/04/13 11:56:38 [error] 21#21: *15 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET /api/get_rooms_data HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc", referrer: "http://heater-new.loc/"
2023/04/13 11:56:41 [error] 21#21: *18 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET /debug HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc", referrer: "http://heater-new.loc/"
2023/04/13 11:56:43 [error] 21#21: *17 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc", referrer: "http://heater-new.loc/debug"
2023/04/13 11:56:44 [error] 21#21: *17 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET /api/get_rooms_data HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc", referrer: "http://heater-new.loc/"
2023/04/13 11:56:46 [error] 21#21: *19 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc", referrer: "http://heater-new.loc/debug"
2023/04/13 11:56:47 [error] 21#21: *19 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 192.168.64.1, server: heater-new.loc, request: "GET /api/get_rooms_data HTTP/1.1", upstream: "fastcgi://192.168.64.4:9000", host: "heater-new.loc", referrer: "http://heater-new.loc/"
2023/05/03 04:49:12 [error] 21#21: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.29.0.1, server: heater-new.home-kl.pp.ua, request: "POST /api/post_files_data HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "192.168.200.57", referrer: "http://192.168.200.57/debug"
2023/05/03 04:49:56 [error] 21#21: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.29.0.1, server: heater-new.home-kl.pp.ua, request: "POST /api/post_files_data HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "192.168.200.57", referrer: "http://192.168.200.57/debug"
2023/05/03 04:50:56 [error] 21#21: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.29.0.1, server: heater-new.home-kl.pp.ua, request: "POST /api/post_files_data HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "192.168.200.57", referrer: "http://192.168.200.57/debug"
2023/05/03 04:51:56 [error] 21#21: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.29.0.1, server: heater-new.home-kl.pp.ua, request: "POST /api/post_files_data HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host: "192.168.200.57", referrer: "http://192.168.200.57/debug"
